const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={date:new Date(),view:'month',editing:null,mini:new Date(new Date().getFullYear(),new Date().getMonth(),1),events:JSON.parse(localStorage.getItem('hearth-events')||'[]')};
const colors={mike:'blue',work:'green',birthdays:'pink',holidays:'gray'};const calendarNames={mike:'Mike Johnson',work:'Work',birthdays:'Birthdays',holidays:'Holidays'};
let googleConnected=false;
function save(){localStorage.setItem('hearth-events',JSON.stringify(state.events))}function iso(d){return d.toISOString().slice(0,10)}function fmtMonth(d){return d.toLocaleString('en-US',{month:'long',year:'numeric'})}function daysInMonth(y,m){return new Date(y,m+1,0).getDate()}
async function api(path,options={}){let r=await fetch(path,options);if(!r.ok){let x=await r.json().catch(()=>({}));throw Error(x.error||'Request failed')}return r.status===204?null:r.json()}
async function setSyncStatus(){try{let s=await api('/api/google/status');googleConnected=s.connected;$('#syncStatus').textContent=s.connected?'Connected · ready to sync':s.configured?'Not connected':'Setup required';$('#connectBtn').textContent=s.connected?'Sync now':'Connect';$('#syncNote').textContent=s.configured?'You will securely sign in using your Google account.':'Add Google OAuth values to .env before connecting.'}catch{googleConnected=false}}
async function syncFromGoogle(){if(!googleConnected)return;try{let remote=await api('/api/google/events'),initial=!localStorage.getItem('hearth-google-initial-sync-v2');if(initial){let demos=new Set(['Design review','Lunch with Sam','Project kickoff','Dad’s birthday','Team offsite','Coffee catch-up']),demoIds=state.events.filter(x=>demos.has(x.title)&&x.googleEventId).map(x=>x.googleEventId);for(const id of demoIds)await api(`/api/google/events/${encodeURIComponent(id)}`,{method:'DELETE'});state.events=remote.events.filter(x=>!demoIds.includes(x.googleEventId));localStorage.setItem('hearth-google-initial-sync-v2','true')}else{let ids=new Set(state.events.map(x=>x.googleEventId));state.events=[...state.events,...remote.events.filter(x=>!ids.has(x.googleEventId))]}save();render();$('#syncStatus').textContent='Connected · synced just now';toast(initial?'Imported your Google Calendar':'Calendar synced with Google')}catch(e){toast(e.message)}}
async function syncEvent(event){if(!googleConnected)return;try{let saved=await api('/api/google/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(event)});event.googleEventId=saved.googleEventId;event.updated=saved.updated;save()}catch(e){toast(`Saved locally: ${e.message}`)}}
async function deleteSyncedEvent(event){if(!googleConnected||!event.googleEventId)return;try{await api(`/api/google/events/${encodeURIComponent(event.googleEventId)}?calendar=${encodeURIComponent(event.googleCalendarId||'primary')}`,{method:'DELETE'})}catch(e){toast(`Deleted locally: ${e.message}`)}}
function activeEvents(){const enabled=new Set($$('.cal-check input:checked').map(x=>x.dataset.calendar));return state.events.filter(e=>enabled.has(e.calendar))}
function renderMini(){const d=state.mini,y=d.getFullYear(),m=d.getMonth();$('#miniTitle').textContent=fmtMonth(d);let html='';let offset=new Date(y,m,1).getDay(),total=daysInMonth(y,m),prev=daysInMonth(y,m-1);for(let i=0;i<42;i++){let n=i-offset+1,cls='';let date;if(n<1){n=prev+n;cls='outside';date=new Date(y,m-1,n)}else if(n>total){n-=total;cls='outside';date=new Date(y,m+1,n)}else date=new Date(y,m,n);if(iso(date)===iso(state.date))cls+=' selected';html+=`<button class="${cls}" data-mini="${iso(date)}">${n}</button>`}$('#miniCalendar').innerHTML=html}
function renderMonth(){let base=new Date(state.date.getFullYear(),state.date.getMonth(),1),start=new Date(base);start.setDate(1-base.getDay());$('#periodTitle').textContent=fmtMonth(state.date);let html='';for(let i=0;i<35;i++){let d=new Date(start);d.setDate(start.getDate()+i);let date=iso(d),other=d.getMonth()!==state.date.getMonth(),today=date==='2026-09-14';let events=activeEvents().filter(e=>e.date===date);html+=`<div class="day-cell ${other?'other-month':''} ${today?'today':''}" data-date="${date}"><span class="day-number">${d.getDate()}</span>${events.map(e=>`<div class="event ${colors[e.calendar]}" data-id="${e.id}" title="${e.title}">${e.allDay?'':e.time+' '}${e.title}</div>`).join('')}</div>`}$('#monthGrid').innerHTML=html}
function renderWeek(){let start=new Date(state.date),count=state.view==='day'?1:7;if(state.view!=='day')start.setDate(start.getDate()-start.getDay());let html='<div>';for(let h=0;h<24;h++)html+=`<div class="week-time">${h===0?'':(h>12?h-12:h)+(h>=12?' PM':' AM')}</div>`;html+='</div>';for(let i=0;i<count;i++){let d=new Date(start);d.setDate(start.getDate()+i),date=iso(d),today=date==='2026-09-14';html+=`<div class="week-day ${today?'current':''}" data-date="${date}"><header>${d.toLocaleString('en',{weekday:'short'}).toUpperCase()}<b>${d.getDate()}</b></header>${activeEvents().filter(e=>e.date===date).map(e=>{let [h,min]=(e.time||'00:00').split(':').map(Number),[eh,emin]=(e.end||e.time||'00:30').split(':').map(Number),duration=e.allDay?25:Math.max(25,(eh*60+emin)-(h*60+min));return `<div class="week-event ${colors[e.calendar]}" data-id="${e.id}" style="top:${48+h*60+min}px;height:${duration}px">${e.title}</div>`}).join('')}</div>`}$('#weekView').innerHTML=html}
function renderSchedule(){let ev=activeEvents().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));let groups={};ev.forEach(e=>(groups[e.date]??=[]).push(e));$('#scheduleView').innerHTML=Object.entries(groups).map(([d,list])=>`<section class="schedule-day"><div class="schedule-date">${new Date(d+'T12:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</div>${list.map(e=>`<div class="schedule-item" style="border-color:${e.calendar==='work'?'#0f9d58':e.calendar==='birthdays'?'#d96570':'#4285f4'}" data-id="${e.id}"><b>${e.title}</b><span>${e.allDay?'All day':e.time+' – '+e.end}${e.location?' · '+e.location:''}</span></div>`).join('')}</section>`).join('')||'<p style="color:#70757a">No events found.</p>'}
function render(){renderMini();renderMonth();renderWeek();renderSchedule();$('.month-view').classList.toggle('hidden',state.view!=='month');$('#weekView').classList.toggle('hidden',!['week','day'].includes(state.view));$('#scheduleView').classList.toggle('hidden',state.view!=='schedule');if(state.view==='day')$('#weekView').style.gridTemplateColumns='55px 1fr';else $('#weekView').style.gridTemplateColumns='55px repeat(7,1fr)'}
function openEvent(e,date){state.editing=e||null;$('#eventForm').reset();$('#eventDate').value=e?.date||date||iso(state.date);$('#eventTitle').value=e?.title||'';$('#eventTime').value=e?.time||'10:00';$('#eventEnd').value=e?.end||'11:00';$('#allDay').checked=e?.allDay||false;$('#eventLocation').value=e?.location||'';$('#eventNotes').value=e?.notes||'';$('#eventCalendar').value=e?.calendar||'mike';$('#eventReminder').value=e?.reminder||'10 minutes before';$('#deleteBtn').classList.toggle('hidden',!e);$('#eventModal').classList.remove('hidden');$('#eventTitle').focus()}
function closeModals(){$$('.modal').forEach(x=>x.classList.add('hidden'))}function toast(text){let t=$('#toast');t.textContent=text;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2800)}
$('#createBtn').onclick=()=>openEvent();$('#todayBtn').onclick=()=>{state.date=new Date(2026,8,14);state.mini=new Date(2026,8,1);render()};$('#prevBtn').onclick=()=>{state.date.setMonth(state.date.getMonth()-1);state.mini=new Date(state.date.getFullYear(),state.date.getMonth(),1);render()};$('#nextBtn').onclick=()=>{state.date.setMonth(state.date.getMonth()+1);state.mini=new Date(state.date.getFullYear(),state.date.getMonth(),1);render()};$('.mini-prev').onclick=()=>{state.mini.setMonth(state.mini.getMonth()-1);renderMini()};$('.mini-next').onclick=()=>{state.mini.setMonth(state.mini.getMonth()+1);renderMini()};
document.addEventListener('click',ev=>{let e=ev.target.closest('.event,.week-event,.schedule-item');if(e){ev.stopPropagation();openEvent(state.events.find(x=>x.id==e.dataset.id));return}let cell=ev.target.closest('.day-cell,.week-day');if(cell&&!ev.target.closest('.event'))openEvent(null,cell.dataset.date);let mini=ev.target.closest('[data-mini]');if(mini){state.date=new Date(mini.dataset.mini+'T12:00');state.mini=new Date(state.date.getFullYear(),state.date.getMonth(),1);render()}if(ev.target.closest('.close-modal'))closeModals()});
$('#eventForm').onsubmit=async e=>{e.preventDefault();let data={id:state.editing?.id||Date.now(),googleEventId:state.editing?.googleEventId,title:$('#eventTitle').value,date:$('#eventDate').value,time:$('#eventTime').value,end:$('#eventEnd').value,allDay:$('#allDay').checked,location:$('#eventLocation').value,notes:$('#eventNotes').value,calendar:$('#eventCalendar').value,reminder:$('#eventReminder').value};if(state.editing)state.events=state.events.map(x=>x.id===data.id?data:x);else state.events.push(data);save();closeModals();render();await syncEvent(data);toast(state.editing?'Event updated':'Event created')};$('#deleteBtn').onclick=async()=>{let old=state.editing;state.events=state.events.filter(x=>x.id!==old.id);save();closeModals();render();await deleteSyncedEvent(old);toast('Event deleted')};$$('.cal-check input').forEach(x=>x.onchange=render);$$('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render()});
$('#searchInput').oninput=e=>{let q=e.target.value.toLowerCase();$$('.event,.schedule-item,.week-event').forEach(x=>x.style.opacity=!q||x.textContent.toLowerCase().includes(q)?'1':'.15')};$('.menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#connectBtn').onclick=()=>$('#syncModal').classList.remove('hidden');$('#finishConnect').onclick=()=>{closeModals();$('#syncStatus').textContent='Connected · synced just now';$('#connectBtn').textContent='Sync now';toast('Google Calendar connected')};$('#settingsBtn').onclick=()=>toast('Settings are ready for your account preferences.');$('#helpBtn').onclick=()=>toast('Click any day to add an event.');render();lucide.createIcons();
// Replace prototype handlers with real OAuth/sync behavior when served by server.js.
$('#connectBtn').onclick=()=>googleConnected?syncFromGoogle():$('#syncModal').classList.remove('hidden');
$('#finishConnect').onclick=()=>location.assign('/auth/google');
$('#addCalendarBtn').onclick=()=>$('#addCalendarModal').classList.remove('hidden');
$('#addCalendarConnect').onclick=()=>location.assign('/auth/google');
$('#settingsBtn').onclick=()=>toast('Settings are saved automatically in this local calendar.');
$('#helpBtn').onclick=()=>toast('Create an event with + Create, then click it to edit.');
$('#appsBtn').onclick=()=>toast('Google Workspace apps open after you connect your account.');
$('#accountBtn').onclick=()=>toast(googleConnected?'Google Calendar account connected.':'You are using local calendar mode.');
$('#viewMoreBtn').onclick=()=>{let views=['day','week','month','schedule'],next=views[(views.indexOf(state.view)+1)%views.length];$(`[data-view="${next}"]`).click()};
let syncResult=new URLSearchParams(location.search).get('sync');
if(syncResult==='connected'){history.replaceState({},'',location.pathname);toast('Google Calendar connected')}else if(syncResult){toast('Google connection: '+syncResult.replaceAll('-',' '))}
setSyncStatus().then(()=>{if(syncResult==='connected')syncFromGoogle()});

// Free household tools. Supabase can replace this local store when its project keys are configured.
const home=JSON.parse(localStorage.getItem('hearth-home')||'{"tasks":[],"groceries":[]}');
const recipes=[['Chicken & broccoli rice bowl',['chicken','broccoli','rice'],78],['Pasta primavera',['pasta','tomato','spinach'],68],['Vegetable omelet',['eggs','spinach','cheese'],74],['Taco bowls',['ground beef','beans','rice'],71],['Salmon salad',['salmon','lettuce','avocado'],88]];
function saveHome(){localStorage.setItem('hearth-home',JSON.stringify(home))}function rows(items,type){return items.map((x,i)=>`<div class="list-row ${x.done?'checked':''}"><input type="checkbox" data-home="${type}" data-i="${i}" ${x.done?'checked':''}><span>${x.name}</span><button class="delete-item" data-delete="${type}" data-i="${i}">×</button></div>`).join('')||'<p>Nothing here yet.</p>'}
function renderHome(){if(!$('#taskList'))return;$('#taskList').innerHTML=rows(home.tasks,'tasks');$('#groceryList').innerHTML=rows(home.groceries,'groceries');let words=home.groceries.map(x=>x.name.toLowerCase()),matches=recipes.map(r=>({r,have:r[1].filter(i=>words.some(w=>w.includes(i))).length})).filter(x=>x.have).sort((a,b)=>b.have-a.have).slice(0,3);$('#recipeList').innerHTML=matches.map(x=>`<div class="recipe"><b>${x.r[0]}</b><small>${x.have}/${x.r[1].length} key ingredients on your list · health ${x.r[2]}/100</small></div>`).join('')||'<p>Add groceries to find recipe ideas.</p>'}
function addHome(type,id){let input=$(id),name=input.value.trim();if(!name)return;home[type].push({name,done:false});input.value='';saveHome();renderHome()}
$('#taskQuickAdd').onclick=()=>addHome('tasks','#taskInput');$('#groceryQuickAdd').onclick=()=>addHome('groceries','#groceryInput');$('#taskInput').onkeydown=e=>{if(e.key==='Enter')addHome('tasks','#taskInput')};$('#groceryInput').onkeydown=e=>{if(e.key==='Enter')addHome('groceries','#groceryInput')};$('#clearCheckedGroceries').onclick=()=>{home.groceries=home.groceries.filter(x=>!x.done);saveHome();renderHome()};$('#refreshRecipes').onclick=renderHome;
document.addEventListener('change',e=>{if(e.target.dataset.home){home[e.target.dataset.home][e.target.dataset.i].done=e.target.checked;saveHome();renderHome()}});document.addEventListener('click',e=>{let b=e.target.closest('[data-delete]');if(b){home[b.dataset.delete].splice(b.dataset.i,1);saveHome();renderHome()}});
$('#scoreMealBtn').onclick=()=>{let text=$('#mealInput').value.toLowerCase(),good=['vegetable','broccoli','spinach','salmon','chicken','beans','brown rice','avocado','olive oil','fruit'],less=['sugar','fried','bacon','sausage','butter','cream','candy','soda'];let score=50+good.filter(x=>text.includes(x)).length*9-less.filter(x=>text.includes(x)).length*8;score=Math.max(10,Math.min(100,score));$('#mealResult').textContent=`${score}/100 — ${score>75?'Well balanced: strong whole-food choices.':score>55?'A solid start. Add vegetables, fruit, or a whole grain to improve it.':'Try adding vegetables or lean protein and reducing highly processed ingredients.'}`};
$$('[data-app]').forEach(b=>b.onclick=()=>{let homeOpen=b.dataset.app==='household';$$('[data-app]').forEach(x=>x.classList.toggle('active',x===b));$('.calendar-area').classList.toggle('hidden',homeOpen);$('#householdView').classList.toggle('hidden',!homeOpen);$('#sidebar').classList.toggle('hidden',homeOpen);$('#periodTitle').textContent=homeOpen?'Household':'September 2026';if(homeOpen)renderHome()});renderHome();lucide.createIcons();
function applyTheme(dark){document.body.classList.toggle('dark',dark);localStorage.setItem('hearth-dark-mode',dark?'1':'0');$('#themeBtn').setAttribute('aria-label',dark?'Use light mode':'Use dark mode');$('#themeBtn').innerHTML=`<i data-lucide="${dark?'sun':'moon'}"></i>`;lucide.createIcons()}
applyTheme(localStorage.getItem('hearth-dark-mode')==='1');$('#themeBtn').onclick=()=>applyTheme(!document.body.classList.contains('dark'));
