import {escapeHTML as esc} from './calendar-model.js';
export function installCookingMode(){
 document.body.insertAdjacentHTML('beforeend',`<dialog id="cookingDialog" class="cooking-dialog" aria-labelledby="cookingTitle"><div class="dialog-heading"><div><p class="eyebrow">LET'S COOK</p><h2 id="cookingTitle"></h2></div><button class="icon" data-close aria-label="Close cooking mode">×</button></div><p id="cookingScale" class="muted"></p><label class="wake-control"><input id="cookingWake" type="checkbox">Keep screen awake</label><p id="wakeStatus" class="muted" role="status"></p><section class="cooking-timer"><label>Timer minutes<input id="timerMinutes" type="number" min="1" max="240" value="10"></label><button id="startTimer" class="button">Start timer</button><button id="stopTimer" class="text-button">Clear</button><output id="timerDisplay" aria-label="Time remaining">00:00</output><p id="timerStatus" role="status"></p><small>Keep Hearth open. Background notifications are not sent.</small></section><div class="cooking-columns"><section><h3>Ingredients</h3><div id="cookingIngredients"></div></section><section><h3>Method</h3><p id="cookingProgress" role="status"></p><div id="cookingSteps"></div></section></div><button id="finishCooking" class="primary">Finish cooking</button></dialog>`);
 const $=s=>document.querySelector(s);let wake=null,deadline=0,timer=null,finish=null;
 async function requestWake(){if(!$('#cookingWake').checked||document.hidden)return;try{wake=await navigator.wakeLock.request('screen');$('#wakeStatus').textContent='Screen will stay awake while Hearth is visible.';wake.addEventListener('release',()=>{wake=null;$('#wakeStatus').textContent='Screen lock released.';});}catch{$('#cookingWake').checked=false;$('#wakeStatus').textContent='Keeping the screen awake is unavailable on this device.';}}
 $('#cookingWake').onchange=()=>{$('#cookingWake').checked?requestWake():wake?.release();};
 document.addEventListener('visibilitychange',()=>{if($('#cookingDialog').open)requestWake();});
 const tick=()=>{const seconds=Math.max(0,Math.ceil((deadline-Date.now())/1000));$('#timerDisplay').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');if(!seconds&&deadline){deadline=0;clearInterval(timer);$('#timerStatus').textContent='Timer finished.';}};
 $('#startTimer').onclick=()=>{const minutes=Number($('#timerMinutes').value);if(!Number.isFinite(minutes)||minutes<1||minutes>240)return;deadline=Date.now()+minutes*60000;clearInterval(timer);timer=setInterval(tick,250);$('#timerStatus').textContent='Timer running';tick();};
 $('#stopTimer').onclick=()=>{deadline=0;clearInterval(timer);tick();$('#timerStatus').textContent='';};
 $('#cookingDialog').addEventListener('close',()=>{wake?.release();$('#cookingWake').checked=false;$('#stopTimer').click();});
 $('#cookingSteps').onchange=()=>{$('#cookingProgress').textContent=$('#cookingSteps').querySelectorAll('input:checked').length+' of '+$('#cookingSteps').children.length+' steps complete';};
 $('#finishCooking').onclick=()=>{$('#cookingDialog').close();finish?.();};
 return {open(recipe,servings,onFinish){finish=onFinish;$('#cookingTitle').textContent=recipe.name;$('#cookingScale').textContent=servings+' servings. Ingredient amounts are scaled; method describes the original '+recipe.servings+' servings.';$('#cookingIngredients').innerHTML=recipe.portions.map(p=>`<label class="cooking-check"><input type="checkbox"><span>${Math.round(p.amount*servings/recipe.servings*100)/100} ${esc(p.unit)} ${esc(p.name)}</span></label>`).join('');$('#cookingSteps').innerHTML=recipe.steps.map((step,i)=>`<label class="cooking-check"><input type="checkbox"><span><strong>Step ${i+1}</strong>${esc(step)}</span></label>`).join('');$('#cookingSteps').onchange();$('#finishCooking').textContent=onFinish?'Review pantry usage':'Finish cooking';$('#wakeStatus').textContent='';$('#cookingDialog').showModal();}};
}
