import {dateKey,parseDay,addDays,escapeHTML as esc,occursOn} from './calendar-model.js';
import {recipes,hasIngredient} from './recipes.js';
import {stableUUID,normalizedFood} from './planning.js';
import {kinds,recipeFor,migrateMeals,shoppingPreview,cookingPreview,applyChanges,fingerprint,advanceChore,useSoon,aisleFor,foodKey,quantity} from './household-model.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const paths={home:'M3 10 12 3l9 7v11h-6v-7H9v7H3Z',calendar:'M4 5h16v16H4ZM8 2v6m8-6v6M4 10h16',tasks:'m3 6 2 2 4-4m3 2h9M3 14l2 2 4-4m3 2h9M12 21h9',meals:'M5 2v7m3-7v7M2 2v7q0 4 6 4V22M18 2v20m0-20q-6 5 0 11',shopping:'m2 3 3 1 3 13h11l3-10H6M9 21h.01M18 21h.01',edit:'m4 16 12-12 4 4L8 20H4ZM13 7l4 4',close:'m6 6 12 12M6 18 18 6',next:'m9 5 7 7-7 7',prev:'m15 5-7 7 7 7',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',theme:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11',menu:'M3 6h18M3 12h18M3 18h18',star:'m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z',plus:'M12 4v16M4 12h16',stock:'M3 12h17m-6-6 6 6-6 6',account:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M4 22v-3a8 8 0 0 1 16 0v3'};
export const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.plus}"/></svg>`;
const button=(label,attrs='',style='button')=>`<button type="button" class="${style}" ${attrs}>${label}</button>`;
const today=()=>dateKey(new Date());
const unitOptions=['each','g','cup','tbsp','tsp','oz','can','clove','fillet','pinch'];
const options=(list,value='')=>list.map(x=>`<option value="${esc(x)}" ${x===value?'selected':''}>${esc(x)}</option>`).join('');

export function installHousehold(ctx){
 const {state,settings,read,write,homeItems,homeChange,allRecipes,outbox,post,enqueue,flushQueue,cacheAccount,loadHome,toast,person,chip,displayEvents,openCustomRecipeModal,sync}=ctx;
 let selectedRecipe=null,selectedMeal=null,pickerDay=today(),preview=null;
 const currentHome=()=>Object.fromEntries(kinds.map(k=>[k,homeItems(k)]));
 const members=()=>state.shared?state.members:['device'];
 const favorites=()=>read('hearth-favorites-'+(state.shared?state.account:'device'),[]);
 const memberOptions=(value='')=>'<option value="">Anyone</option>'+members().map(m=>`<option value="${esc(m)}" ${m===value?'selected':''}>${esc(person(m))}</option>`).join('');
 const headings={home:['A little more room for life.','Your day, your people, and a plan for dinner.'],tasks:['Make room for what matters.','A shared rhythm for the everyday things.'],meals:['Something good is on the menu.','Plan the week. Cook your favorites. Use what you have.'],shopping:['A thoughtful list. A stocked kitchen.','Everything to pick up, and everything already at home.']};

 // Reuse the existing forms and their accessible labels in focused destinations.
 $('.app-tabs').innerHTML=['home','calendar','tasks','meals','shopping'].map(n=>button(icon(n)+`<span>${n[0].toUpperCase()+n.slice(1)}</span>`,`data-app="${n}"`,'nav-item')).join('');
 $('.brand').innerHTML='<img src="/icon.svg" alt="" width="38" height="38">Hearth';
 $('.brand').onclick=e=>{e.preventDefault();navigate('home');};
 const grid=$('.home-grid'),taskCard=$('#taskForm').closest('article'),groceryCard=$('#groceryForm').closest('article'),pantryCard=$('#pantryForm').closest('article'),recipeCard=$('#recipeList').closest('article'),balanceCard=$('#mealForm').closest('article');
 taskCard.id='tasksPanel';groceryCard.id='groceriesPanel';pantryCard.id='pantryPanel';recipeCard.id='recipesPanel';
 taskCard.dataset.destination='tasks';groceryCard.dataset.destination='shopping';pantryCard.dataset.destination='shopping';recipeCard.dataset.destination='meals';
 $('.week-plan').dataset.destination='meals';$('#dashboard').dataset.destination='home';
 const balance=document.createElement('details');balance.className='card meal-balance';balance.dataset.destination='meals';balance.innerHTML='<summary>Explore meal balance</summary>';balance.append(balanceCard);grid.append(balance);
 $('#homeWorkspace').insertAdjacentHTML('afterbegin','<div id="sectionTools" class="section-tools"></div>');
 $('#homeStatus').outerHTML='<button type="button" class="storage-badge" id="homeStatus" aria-label="Household sync details"></button>';
 $('#homeStatus').onclick=()=>{$('#syncDetailsButton').click();};
 $('#taskForm').insertAdjacentHTML('beforeend',`<details class="task-options"><summary>Assignment & repeat</summary><div class="form-grid"><label>Assigned to<select name="assignedTo" id="createAssignee"></select></label><label>Priority<select name="priority">${options(['normal','high','low'])}</select></label><label>Repeat<select name="repeat">${options(['none','daily','weekly','monthly'])}</select></label></div><fieldset id="createRotation"><legend>Alternate between members</legend></fieldset></details><p class="error" id="taskCreateError" role="alert"></p>`);
 $('#pantryForm').insertAdjacentHTML('beforeend','<label class="compact-field">Expiration (optional)<input name="expires" type="date" aria-label="Pantry expiration date"></label>');
 $('#pantryList').insertAdjacentHTML('beforebegin','<div id="useSoon" class="notice hidden"></div>');
 $('#groceryForm').insertAdjacentHTML('beforeend',`<label class="compact-field">Amount<input name="amount" type="number" min="0" max="100000" step="0.01" aria-label="Grocery amount"></label><label class="compact-field">Unit<select name="unit" aria-label="Grocery unit">${options(unitOptions,'each')}</select></label>`);
 const groceryOptions=document.createElement('details');groceryOptions.className='grocery-options';groceryOptions.innerHTML='<summary>Quantity & notes</summary><div class="grocery-fields"></div>';$('#groceryForm').append(groceryOptions);groceryOptions.querySelector('.grocery-fields').append($('#groceryForm [name=quantity]'),...$$('#groceryForm .compact-field'));
 $('#groceryList').insertAdjacentHTML('beforebegin',`<div class="shopping-tools"><label class="check"><input id="shoppingMode" type="checkbox"> Shopping mode</label>${button('Put purchased items in pantry','id="transferPurchased"')}<p id="shoppingProgress" class="muted" aria-live="polite"></p></div>`);
 $('#recipeList').insertAdjacentHTML('beforebegin',`<div class="recipe-filters"><input id="recipeSearch" type="search" aria-label="Search recipes" placeholder="Find a recipe or ingredient"><select id="recipeTime" aria-label="Preparation time"><option value="0">Any cook time</option><option value="15">15 minutes or less</option><option value="30">30 minutes or less</option><option value="45">45 minutes or less</option></select><label class="check"><input id="recipeFavorites" type="checkbox"> Favorites</label><label class="check"><input id="recipePantry" type="checkbox"> All ingredients at home</label><label class="check"><input id="recipeUseSoon" type="checkbox"> Use soon</label></div><div id="recipeImport"></div>`);
 $('#taskFields').insertAdjacentHTML('beforeend','<fieldset id="editRotation"><legend>Alternate between members</legend></fieldset>');
 $('#inventoryFields').insertAdjacentHTML('beforeend','<label>Expiration date<input id="itemExpires" type="date"></label><label>Aisle<input id="itemAisle" maxlength="60" list="aisles"></label><datalist id="aisles"><option>Produce</option><option>Dairy & eggs</option><option>Meat & seafood</option><option>Frozen</option><option>Pantry & other</option></datalist>');
 $('#itemUnit').innerHTML=options(unitOptions);
 const more=document.createElement('details');more.id='eventMore';more.innerHTML='<summary>More options</summary>';
 const location=$('#eventLocation').closest('label'),repeat=$('#eventRepeat').closest('.form-grid');location.before(more);more.append(location,$('#eventReminder').closest('label'),repeat,$('#eventNotes').closest('label'));
 $('#eventForm').addEventListener('invalid',e=>{if(more.contains(e.target))more.open=true;},true);
 document.body.insertAdjacentHTML('beforeend',`<dialog id="pickerDialog"><div class="dialog-heading"><h2>Choose something good</h2>${button(icon('close'),'data-close aria-label="Close recipe picker"','icon')}</div><p id="pickerDate" class="muted"></p><div id="pickerFilters"></div><div id="pickerRecipes"></div></dialog><dialog id="previewDialog"><form id="previewForm"><div class="dialog-heading"><h2 id="previewTitle"></h2>${button(icon('close'),'data-close aria-label="Close preview"','icon')}</div><p id="previewDescription" class="muted"></p><div id="previewWarnings" class="notice hidden"></div><div id="previewRows"></div><p id="previewError" class="error" role="alert"></p><div class="dialog-actions">${button('Cancel','data-close')}<button class="primary" id="confirmPreview">Confirm changes</button></div></form></dialog><dialog id="postponeDialog"><form id="postponeForm"><div class="dialog-heading"><h2>Postpone this task</h2>${button(icon('close'),'data-close aria-label="Close postpone"','icon')}</div><label>New due date<input id="postponeDate" type="date" required></label><p class="muted">The recurring schedule stays the same.</p><p id="postponeError" class="error" role="alert"></p><button class="primary">Save date</button></form></dialog>`);
 $('#pickerFilters').innerHTML=$('.recipe-filters').outerHTML.replaceAll('recipeSearch','pickerSearch').replaceAll('recipeTime','pickerTime').replaceAll('recipeFavorites','pickerFavorites').replaceAll('recipePantry','pickerPantry').replaceAll('recipeUseSoon','pickerUseSoon').replaceAll('Search recipes','Search recipes to plan');
 $('#recipeDialog .dialog-actions').insertAdjacentHTML('afterbegin',button(icon('star')+' Favorite','id="favoriteRecipe"','button')+button('Made this meal','id="cookMeal"','primary'));
 for(const [id,name] of Object.entries({menuBtn:'menu',themeBtn:'theme',settingsBtn:'settings',miniPrev:'prev',miniNext:'next',prevBtn:'prev',nextBtn:'next',mealWeekPrev:'prev',mealWeekNext:'next'}))$('#'+id).innerHTML=icon(name);
 $$('[data-close]').forEach(b=>{if(b.classList.contains('icon'))b.innerHTML=icon('close');});
 const mobileAccount=$('#accountBtn');mobileAccount.innerHTML=icon('account')+'<span>Account</span>';

 function navigate(destination,refresh=true){
  if(!['home','calendar','tasks','meals','shopping'].includes(destination))destination='home';
  state.app=destination;settings.destination=destination;write('hearth-settings',settings);if(ctx.syncSettingsToPocketBase)ctx.syncSettingsToPocketBase();
  $$('[data-app]').forEach(b=>{b.classList.toggle('active',b.dataset.app===destination);if(b.dataset.app===destination)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
  $('#calendarWorkspace').classList.toggle('hidden',destination!=='calendar');$('#homeWorkspace').classList.toggle('hidden',destination==='calendar');$('#sidebar').classList.toggle('hidden',destination!=='calendar');$('#menuBtn').classList.toggle('hidden',destination!=='calendar');document.body.classList.remove('sidebar-open');
  $$('[data-destination]').forEach(el=>el.classList.toggle('hidden',el.dataset.destination!==destination));
  $('#homeWorkspace').dataset.screen=destination;$('#homeWorkspace').scrollTop=0;
  const heading=headings[destination];if(heading){$('.home-heading h1').innerHTML=`<span class="desktop-heading">${esc(heading[0])}</span><span class="mobile-heading">${esc(destination==='home'?heading[0]:destination[0].toUpperCase()+destination.slice(1))}</span>`;$('.home-heading p:last-child').textContent=heading[1];$('.eyebrow').textContent=destination==='home'?'WELCOME HOME':destination.toUpperCase();}
  render();if(refresh){if(destination!=='calendar')loadHome();sync();}
 }
 $$('[data-app]').forEach(b=>b.onclick=()=>navigate(b.dataset.app));

 function rotationFields(target,selected=[]){const list=members();$('#'+target).innerHTML='<legend>Alternate between members</legend>'+list.map(m=>`<label class="check"><input type="checkbox" value="${esc(m)}" ${selected.includes(m)?'checked':''} ${list.length<2?'disabled':''}>${esc(person(m))}</label>`).join('')+(list.length<2?'<p class="muted">Available with two or more household members.</p>':'');}
 function updateMembers(){const key=members().join('|');if($('#createAssignee').dataset.members===key)return;$('#createAssignee').innerHTML=memberOptions();$('#createAssignee').dataset.members=key;rotationFields('createRotation');}
 function prepareItem(item){$('#itemExpires').value=item.expires||'';$('#itemAisle').value=item.aisle||aisleFor(item.name);$('#itemAisle').closest('label').classList.toggle('hidden',item.kind!=='groceries');$('#itemAssignee').innerHTML=memberOptions(item.assignedTo);rotationFields('editRotation',item.rotation||[]);}
 function itemFields(){return {expires:$('#itemExpires').value,aisle:$('#itemAisle').value,rotation:$$('#editRotation input:checked').map(e=>e.value)};}
 function row(item,kind){return `<div class="list-row ${item.done?'done':''} ${kind==='tasks'&&!item.done&&item.due&&item.due<today()?'overdue':''}">${kind!=='pantry'?`<label class="checkbox-target"><input type="checkbox" aria-label="Complete ${esc(item.name)}" data-check="${esc(item.id)}" data-kind="${kind}" ${item.done?'checked':''}></label>`:icon('shopping')}<span class="item-copy"><strong>${esc(item.name)}</strong>${item.pending?'<span class="pending-label">Waiting to sync</span>':''}<small>${esc([item.due,item.amount!=null?item.amount+' '+(item.unit||'each'):item.quantity,item.assignedTo?person(item.assignedTo):'',item.priority==='high'?'High priority':'',item.repeat&&item.repeat!=='none'?'Repeats '+item.repeat:'',item.expires?'Expires '+item.expires:'',item.skipped?'Skipped':''].filter(Boolean).join(' · '))}</small></span><div class="row-actions">${kind==='tasks'&&!item.done?button('Postpone',`data-postpone="${item.id}"`,'text-button')+(item.repeat&&item.repeat!=='none'?button('Skip',`data-skip="${item.id}"`,'text-button'):''):''}${kind==='groceries'?button(icon('stock'),`data-stock="${item.id}" aria-label="Move ${esc(item.name)} to pantry"`,'icon'):''}${button(icon('edit'),`data-edit-item="${item.id}" data-kind="${kind}" aria-label="Edit ${esc(item.name)}"`,'icon')}${button(icon('close'),`data-delete-item="${item.id}" data-kind="${kind}" aria-label="Delete ${esc(item.name)}"`,'icon')}</div></div>`;}
 function renderTasks(){const filter=$('#taskFilter').value;let tasks=homeItems('tasks').filter(t=>filter==='all'||filter==='done'&&t.done||filter==='mine'&&!t.done&&t.assignedTo===(state.shared?state.account:'device')||filter==='upcoming'&&!t.done);tasks.sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')||({high:0,normal:1,low:2}[a.priority||'normal']-{high:0,normal:1,low:2}[b.priority||'normal']));
  $('#taskList').innerHTML=['Overdue','Today','Later','Completed'].map(group=>{const list=tasks.filter(t=>(t.done?'Completed':t.due&&t.due<today()?'Overdue':t.due===today()?'Today':'Later')===group);return list.length?`<section class="list-group"><h3>${group}<span>${list.length}</span></h3>${list.map(t=>row(t,'tasks')).join('')}</section>`:'';}).join('')||'<div class="empty empty-illustrated"><img src="/images/empty-tasks.jpg" class="empty-art" alt=""><strong>A little breathing room.</strong><p>Add a task above when something needs doing.</p></div>';
 }
 function renderShopping(){const groceries=homeItems('groceries'),active=groceries.filter(i=>!i.done),done=groceries.filter(i=>i.done),aisles=[...new Set(active.map(i=>i.aisle||aisleFor(i.name)))].sort();
  $('#shoppingProgress').textContent=`${done.length} of ${groceries.length} picked up · ${active.length} remaining`;
  $('#transferPurchased').disabled=!done.length;
  $('#groceryList').innerHTML=aisles.map(a=>`<section class="list-group"><h3>${esc(a)}</h3>${active.filter(i=>(i.aisle||aisleFor(i.name))===a).map(i=>row(i,'groceries')).join('')}</section>`).join('')+(done.length?`<details class="purchased"><summary>Purchased (${done.length})</summary>${done.map(i=>row(i,'groceries')).join('')}</details>`:'')||'<div class="empty empty-illustrated"><img src="/images/empty-kitchen.jpg" class="empty-art" alt=""><strong>You’re all stocked up.</strong><p>Add an item or build a list from your meals.</p></div>';
  const pantry=homeItems('pantry');$('#pantryList').innerHTML=pantry.map(i=>row(i,'pantry')).join('')||'<div class="empty empty-illustrated"><img src="/images/empty-kitchen.jpg" class="empty-art" alt=""><p class="muted">Add what’s in your kitchen to get useful meal matches.</p></div>';
  const soon=useSoon(pantry);$('#useSoon').classList.toggle('hidden',!soon.length);$('#useSoon').innerHTML='<strong>Use soon</strong><p>'+soon.map(i=>esc(i.name)+' · '+(i.expires<today()?'date passed':esc(i.expires))).join('<br>')+'</p>'+button('Find meals to use these','id="findUseSoon"','text-button');
 }
 function recipeCards(prefix='recipe',target='#recipeList',picking=false){const q=$('#'+prefix+'Search').value.toLowerCase().trim(),max=Number($('#'+prefix+'Time').value),fav=favorites(),pantry=homeItems('pantry').filter(i=>i.amount>0),groceries=homeItems('groceries'),soon=useSoon(pantry);
  const list=allRecipes().map(r=>({...r,owned:r.ingredients.filter(i=>hasIngredient(pantry,i)).length,listed:r.ingredients.filter(i=>!hasIngredient(pantry,i)&&hasIngredient(groceries,i)).length})).filter(r=>(!q||(r.name+' '+r.ingredients.join(' ')).toLowerCase().includes(q))&&(!max||r.minutes<=max)&&(!$('#'+prefix+'Favorites').checked||fav.includes(r.id))&&(!$('#'+prefix+'Pantry').checked||r.owned===r.ingredients.length)&&(!$('#'+prefix+'UseSoon').checked||r.ingredients.some(i=>hasIngredient(soon,i)))).sort((a,b)=>b.owned/b.ingredients.length-a.owned/a.ingredients.length);
  $(target).innerHTML=list.map(r=>`<button class="recipe-button" ${picking?'data-pick':'data-recipe'}="${esc(r.id)}"><span class="recipe-art">${r.image?`<img src="${esc(r.image)}" alt="" class="recipe-thumb" loading="lazy">`:icon('meals')}</span><span><strong>${esc(r.name)} ${r.custom?'<span class="custom-badge">Custom</span>':''}</strong><small>${r.minutes} min · ${r.servings} servings ${fav.includes(r.id)?' · Favorite':''}</small><small>${r.owned}/${r.ingredients.length} ingredients at home · ${r.listed} on shopping list</small></span>${icon('next')}</button>`).join('')||'<p class="empty">No matching recipes. Try another search or clear a filter.</p>';
 }
 function renderWeek(){const first=state.mealWeek;$('#mealWeekTitle').textContent=first.toLocaleDateString(undefined,{month:'short',day:'numeric'})+' – '+addDays(first,6).toLocaleDateString(undefined,{month:'short',day:'numeric'});$('#mealWeekGrid').innerHTML=Array.from({length:7},(_,i)=>{const d=addDays(first,i),key=dateKey(d);return `<section class="meal-day ${key===today()?'is-today':''}"><strong>${esc(d.toLocaleDateString(undefined,{weekday:'short',day:'numeric'}))}</strong>${homeItems('meals').filter(m=>m.due===key).map(m=>`<div class="planned-meal">${button(esc(m.name),`data-planned-meal="${m.id}"`,'text-button')}<small>${m.servings} servings${m.done?' · Cooked':''}</small>${!m.done?button('Made this meal',`data-cook="${m.id}"`,'text-button'):''}${button(icon('close'),`data-delete-item="${m.id}" data-kind="meals" aria-label="Remove ${esc(m.name)}"`,'icon')}</div>`).join('')}${button(icon('plus')+' Plan',`data-plan-day="${key}"`)}</section>`;}).join('');}
 function dashboard(){if(state.app!=='home'){$('#dashboard').innerHTML='';return;}const events=displayEvents().filter(e=>!state.hidden.includes(e.googleCalendarId||'local')&&occursOn(e,today())),tasks=homeItems('tasks').filter(t=>!t.done).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,3),meals=homeItems('meals').filter(m=>m.due===today());
  $('#dashboard').innerHTML=`<article class="card day-card"><p class="eyebrow">${esc(new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}))}</p><h2>Your day at a glance</h2>${events.slice(0,5).map(chip).join('')||'<p class="muted">A clear calendar. A little room to breathe.</p>'}${button('Open calendar '+icon('next'),'data-go="calendar"','text-button')}</article><article class="card"><p class="eyebrow">A LITTLE TEAMWORK</p><h2>On your list</h2>${tasks.map(t=>`<label class="dashboard-task"><input type="checkbox" data-check="${t.id}" data-kind="tasks" aria-label="Complete ${esc(t.name)}"><span>${esc(t.name)}<small class="${t.due&&t.due<today()?'error':'muted'}">${esc(t.due||'Anytime')}</small></span></label>`).join('')||'<p class="muted">Nothing urgent. Enjoy the moment.</p>'}${button('View tasks '+icon('next'),'data-go="tasks"','text-button')}</article><article class="card dinner-card"><p class="eyebrow">GATHER AROUND</p><h2>Tonight’s table</h2>${meals.map(m=>{const r=recipeFor(m,allRecipes());return `<div class="dinner-preview">${r?.image?`<img src="${esc(r.image)}" alt="${esc(m.name)}" class="dinner-thumb">`:''}<div><strong>${esc(m.name)}</strong><p class="muted">${m.servings} servings${m.done?' · Cooked':''}</p>${button('Change meal',`data-change-meal="${m.id}"`)} ${!m.done?button('Made this meal',`data-cook="${m.id}"`,'primary'):''}</div></div>`;}).join('')||'<p>Something delicious starts with a little plan.</p>'+button('Choose tonight’s dinner',`data-plan-day="${today()}"`,'primary')}</article><article class="card shopping-summary"><div><p class="eyebrow">READY FOR THE WEEK</p><h2>${homeItems('groceries').filter(i=>!i.done).length} things to pick up</h2><p class="muted">${useSoon(homeItems('pantry')).length} pantry items to use soon</p></div>${button('Open shopping list '+icon('next'),'data-go="shopping"','primary')}</article>`;
 }
 function render(){updateMembers();$('#homeStatus').textContent=state.shared?(outbox.forAccount(state.account).some(o=>o.status==='failed')?'Sync needs attention':outbox.forAccount(state.account).length?'Changes waiting to sync':state.lastError?'Refresh needs attention':'Shared household · synced'):'Saved on this device';renderTasks();renderShopping();renderWeek();recipeCards();dashboard();$('#recipeImport').innerHTML=state.shared&&read('hearth-home',{}).recipes?.length?button('Import recipes from this device','id="importRecipes"','text-button'):'';}

 function openPicker(day,meal=null){pickerDay=day;selectedMeal=meal;$('#pickerDate').textContent='Planning for '+parseDay(day).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});recipeCards('picker','#pickerRecipes',true);$('#pickerDialog').showModal();$('#pickerSearch').focus();}
 function openRecipe(id,day=today(),meal=null){const r=meal?.recipeSnapshot||allRecipes().find(r=>r.id===id)||recipeFor(meal||{recipeId:id},allRecipes());if(!r){openPicker(day,meal);toast('Choose a replacement recipe for this meal.');return;}selectedRecipe=r;selectedMeal=meal;$('#recipeTitle').textContent=r.name;$('#recipeServings').value=meal?.servings||r.servings;$('#recipeDate').value=day;renderRecipe();$('#recipeDialog').showModal();}
 function openMeal(meal){openRecipe(meal.recipeId,meal.due,meal);}
 function renderRecipe(){if(!selectedRecipe)return;const r=selectedRecipe,n=Math.max(1,Math.min(20,Number($('#recipeServings').value)||r.servings));const hero=r.image?`<div class="recipe-hero"><img src="${esc(r.image)}" alt="${esc(r.name)}"></div>`:'';$('#recipeDetails').innerHTML=hero+'<h3>Ingredients for '+n+'</h3><ul>'+r.portions.map(p=>`<li>${quantity(p.amount*n/r.servings)} ${esc(p.unit+' '+p.name)}</li>`).join('')+'</ul><h3>Method</h3><p class="muted">Directions describe the original '+r.servings+' servings. Use the ingredient quantities above when scaling.</p><ol>'+r.steps.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol>';const editable=r.custom&&allRecipes().some(x=>x.id===r.id);$('#deleteRecipeBtn').classList.toggle('hidden',!editable);$('#editRecipeBtn').classList.toggle('hidden',!editable);$('#cookMeal').classList.toggle('hidden',!selectedMeal||selectedMeal.done);$('#favoriteRecipe').setAttribute('aria-pressed',String(favorites().includes(r.id)));$('#planRecipe').textContent=selectedMeal?'Save meal':'Plan this meal';}

 function snapshot(){return kinds.flatMap(k=>homeItems(k).map(i=>({id:i.id,updated_at:i.updated_at||null}))).sort((a,b)=>a.id.localeCompare(b.id));}
 async function batch(label,changes,expected=snapshot()){
  if(!changes.length){toast('Nothing to change.');return;}
  if(state.shared&&state.account==='device')throw Error('Reconnect your Google account before changing shared items.');
  if(state.shared&&outbox.forAccount(state.account).some(o=>o.status==='failed'))throw Error('Open Sync details to discard the failed operation, then refresh and review again.');const actor=state.shared?state.account:'device';changes=changes.map(c=>({...c,item:{...c.item,createdBy:c.item.createdBy||actor,updatedBy:actor,completedBy:c.item.done?actor:null}}));
  if(!state.shared){const next=applyChanges(state.home,changes);localStorage.setItem('hearth-home',JSON.stringify(next));state.home=next;render();if(ctx.syncPocketBaseBatch)ctx.syncPocketBaseBatch(changes);return;}
  state.homeGeneration=(state.homeGeneration||0)+1;const op=enqueue({type:'batch',action:'apply',item:{name:label},changes,expected,account:state.account,shared:true});render();await flushQueue();const pending=outbox.rows.find(o=>o.id===op.id);if(pending?.status==='failed'){outbox.remove(op.id);render();throw Error(pending.error);}if(pending)toast('Saved offline · waiting to sync');
 }
 function showPreview(title,description,rows,build,warnings=[]){preview={rows,build,account:state.account,shared:state.shared,fingerprint:fingerprint(currentHome()),expected:snapshot()};$('#previewTitle').textContent=title;$('#previewDescription').textContent=description;$('#previewError').textContent='';$('#previewWarnings').classList.toggle('hidden',!warnings.length);$('#previewWarnings').textContent=warnings.join(' ');$('#previewRows').innerHTML=rows.map((r,i)=>`<label class="preview-row"><span><strong>${esc(r.name)}</strong><small>${esc(r.note||'')}${r.expires?' · Expires '+esc(r.expires):''}</small></span><span class="quantity-input"><input type="number" aria-label="${esc(r.name)} quantity" data-preview="${i}" min="0" max="${r.maximum??100000}" step="0.01" value="${r.amount}" required><span>${esc(r.unit||'each')}</span></span></label>`).join('')||'<p class="muted">No pantry quantities to deduct. You can still mark this meal cooked.</p>';$('#confirmPreview').disabled=false;$('#previewDialog').showModal();}
 $('#previewForm').onsubmit=async e=>{e.preventDefault();$('#confirmPreview').disabled=true;try{if(!preview||preview.account!==state.account||preview.shared!==state.shared||preview.fingerprint!==fingerprint(currentHome()))throw Error('Household changed. Close this preview, refresh, and review again.');const rows=preview.rows.map((r,i)=>({...r,amount:Number($(`[data-preview="${i}"]`).value)}));if(rows.some(r=>!Number.isFinite(r.amount)||r.amount<0||r.amount>(r.maximum??100000)))throw Error('Check the quantities.');await batch($('#previewTitle').textContent,await preview.build(rows),preview.expected);$('#previewDialog').close();toast(state.shared&&outbox.forAccount(state.account).length?'Changes saved - waiting to sync':'Changes saved');}catch(err){$('#previewError').textContent=err.message;}finally{$('#confirmPreview').disabled=false;}};
 async function shopping(meals){const rows=shoppingPreview(meals,allRecipes(),homeItems('pantry'),homeItems('groceries'));if(!rows.length)return toast('Plan a meal first.');showPreview('Review your shopping list','Adjust what to add. Quantities in different units stay separate.',rows.map(r=>({...r,note:`Needs ${r.required} · At home ${r.owned} · Already listed ${r.listed}`})),adjusted=>adjusted.filter(r=>r.amount>0).map(r=>{const existing=homeItems('groceries').find(i=>!i.done&&foodKey(i)===foodKey(r));return {item:{...existing,id:existing?.id||crypto.randomUUID(),kind:'groceries',name:r.name,amount:quantity((existing?.amount||0)+r.amount),unit:r.unit,done:false,aisle:existing?.aisle||aisleFor(r.name)}};}),rows.map(r=>r.warning).filter(Boolean));}
 function transfer(items){items=items.filter(Boolean);if(!items.length)return toast('Check purchased items first.');showPreview('Put groceries away','Confirm the quantities you brought home. Items leave the shopping list after transfer.',items.map(i=>({...i,amount:i.amount||0,note:i.quantity||'Enter the amount purchased'})),rows=>{const next=new Map(homeItems('pantry').map(i=>[i.id,{...i}])),changes=[];for(const r of rows){if(r.amount<=0)continue;let stock=[...next.values()].find(p=>foodKey(p)===foodKey(r)&&(p.expires||'')===(r.expires||''));stock={...stock,id:stock?.id||crypto.randomUUID(),kind:'pantry',name:r.name,unit:r.unit,expires:r.expires||'',amount:quantity((stock?.amount||0)+r.amount),done:false};next.set(stock.id,stock);changes.push({item:homeItems('groceries').find(i=>i.id===r.id),remove:true});}const changed=rows.filter(r=>r.amount>0);return [...changes,...[...next.values()].filter(p=>changed.some(r=>foodKey(r)===foodKey(p)&&(r.expires||'')===(p.expires||''))).map(item=>({item}))];});}
 function cook(meal){if(meal.done)return toast('This meal is already marked cooked.');try{const {rows,warnings}=cookingPreview(meal,allRecipes(),homeItems('pantry'));showPreview('Made '+meal.name,'Review pantry amounts used. Stock with the earliest expiration comes first.',rows.map(r=>({...r,note:'Available '+r.maximum+' '+r.unit})),adjusted=>[...adjusted.map(r=>({item:{...homeItems('pantry').find(i=>i.id===r.id),amount:quantity(r.maximum-r.amount)}})),{item:{...meal,done:true}}],warnings);}catch(e){toast(e.message);openPicker(meal.due,meal);}}
 async function complete(kind,item,done,skipped=false){if(!item)return;try{if(kind==='tasks'&&done&&!item.done){const changes=(await advanceChore(item,skipped)).filter((c,i)=>i===0||!homeItems('tasks').some(t=>t.id===c.item.id));await batch(skipped?'Skip chore':'Complete chore',changes);}else await homeChange(kind,{...item,done});}catch(e){toast(e.message);render();}}
 async function migrateLocal(){const old=read('hearth-home',{}),legacy=read('hearth-custom-recipes',[]);let changed=false;old.recipes||=[];for(const r of old.legacyRecipeMigrationComplete?[]:legacy){const id=await stableUUID('legacy-recipe|'+r.id);if(!old.recipes.some(x=>x.id===id)){old.recipes.push({...r,id,kind:'recipes'});changed=true;}}if(!old.legacyRecipeMigrationComplete){old.legacyRecipeMigrationComplete=true;changed=true;}for(const k of kinds){old[k]||=[];old[k]=old[k].map(item=>{if(!item.id){changed=true;return {...item,id:crypto.randomUUID(),kind:k};}return {...item,kind:k};});}const migrated=migrateMeals(old.meals,[...recipes,...old.recipes]);if(JSON.stringify(migrated)!==JSON.stringify(old.meals)){old.meals=migrated;changed=true;}if(changed)localStorage.setItem('hearth-home',JSON.stringify(old));if(!state.shared)state.home={...state.home,...old};}
 async function migrateShared(){if(!state.shared||outbox.forAccount(state.account).some(o=>o.type!=='event'))return;const meals=homeItems('meals'),migrated=migrateMeals(meals,allRecipes()),changes=migrated.filter((m,i)=>JSON.stringify(m)!==JSON.stringify(meals[i])).map(item=>({item})).slice(0,200);if(changes.length)await batch('Update planned recipe references',changes);}
 async function importRecipes(){const local=read('hearth-home',{}).recipes||[],existing=homeItems('recipes');const changes=local.filter(r=>!existing.some(e=>e.id===r.id)).map(item=>({item}));try{await batch('Import device recipes',changes);toast(changes.length?'Device recipes imported':'These recipes are already in your household.');}catch(e){toast(e.message);}}

 $('#taskForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),rotation=$$('#createRotation input:checked').map(i=>i.value),repeat=f.get('repeat'),due=f.get('due'),name=f.get('name').trim();$('#taskCreateError').textContent='';if(repeat!=='none'&&!due){$('#taskCreateError').textContent='Add a due date for a recurring chore.';return;}const b=e.target.querySelector('button');b.disabled=true;try{await homeChange('tasks',{id:crypto.randomUUID(),name,due,scheduledDue:due,seriesAnchor:due,repeat,priority:f.get('priority'),assignedTo:f.get('assignedTo')||rotation[0]||'',rotation,done:false});e.target.reset();}catch(err){$('#taskCreateError').textContent=err.message;}finally{b.disabled=false;}};
 $('#groceryForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),b=e.target.querySelector('button');b.disabled=true;try{await homeChange('groceries',{id:crypto.randomUUID(),name:f.get('name').trim(),quantity:f.get('quantity'),amount:Number(f.get('amount'))||0,unit:f.get('unit'),done:false});e.target.reset();}catch{}finally{b.disabled=false;}};
 $('#pantryForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),b=e.target.querySelector('button');b.disabled=true;try{await homeChange('pantry',{id:crypto.randomUUID(),name:f.get('name').trim(),amount:Number(f.get('amount'))||0,unit:f.get('unit'),expires:f.get('expires'),done:false});e.target.reset();}catch{}finally{b.disabled=false;}};
 $('#taskFilter').onchange=renderTasks;$('#shoppingMode').onchange=e=>groceryCard.classList.toggle('shopping-mode',e.target.checked);$('#transferPurchased').onclick=()=>transfer(homeItems('groceries').filter(i=>i.done));
 for(const prefix of ['recipe','picker'])for(const suffix of ['Search','Time','Favorites','Pantry','UseSoon'])$('#'+prefix+suffix).addEventListener(suffix==='Search'?'input':'change',()=>recipeCards(prefix,prefix==='picker'?'#pickerRecipes':'#recipeList',prefix==='picker'));
 $('#recipeServings').oninput=renderRecipe;
 $('#favoriteRecipe').onclick=()=>{const list=favorites(),id=selectedRecipe.id;write('hearth-favorites-'+(state.shared?state.account:'device'),list.includes(id)?list.filter(x=>x!==id):[...list,id]);renderRecipe();recipeCards();if(ctx.syncSettingsToPocketBase)ctx.syncSettingsToPocketBase();};
 $('#planRecipe').onclick=async()=>{const servings=Number($('#recipeServings').value),due=$('#recipeDate').value;if(!due||!Number.isFinite(servings)||servings<1||servings>20)return toast('Choose a date and between 1 and 20 servings.');$('#planRecipe').disabled=true;try{await homeChange('meals',{...selectedMeal,id:selectedMeal?.id||crypto.randomUUID(),name:selectedRecipe.name,recipeId:selectedRecipe.id,recipeSnapshot:structuredClone(selectedRecipe),servings,due,done:selectedMeal?.done||false});$('#recipeDialog').close();toast('Meal planned');}catch{}finally{$('#planRecipe').disabled=false;}};
 $('#addIngredients').onclick=async()=>{try{await shopping([{recipeId:selectedRecipe.id,recipeSnapshot:selectedRecipe,servings:Number($('#recipeServings').value)||selectedRecipe.servings}]);$('#recipeDialog').close();}catch(e){toast(e.message);}};
 $('#buildShopping').onclick=async()=>{try{await shopping(homeItems('meals').filter(m=>!m.done&&m.due>=dateKey(state.mealWeek)&&m.due<dateKey(addDays(state.mealWeek,7))));}catch(e){toast(e.message);}};
 $('#cookMeal').onclick=()=>{const meal=selectedMeal;$('#recipeDialog').close();cook(meal);};
 $('#editRecipeBtn').onclick=()=>{const current=allRecipes().find(r=>r.id===selectedRecipe.id);$('#recipeDialog').close();openCustomRecipeModal(current);};
 $('#deleteRecipeBtn').onclick=async()=>{if(!confirm('Delete “'+selectedRecipe.name+'”? Planned meals keep their recipe.'))return;try{await homeChange('recipes',selectedRecipe,true);$('#recipeDialog').close();}catch{}};
 let postponed=null;$('#postponeForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('.primary');b.disabled=true;try{await homeChange('tasks',{...postponed,due:$('#postponeDate').value,scheduledDue:postponed.scheduledDue||postponed.due});$('#postponeDialog').close();}catch(err){$('#postponeError').textContent=err.message;}finally{b.disabled=false;}};
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go)navigate(b.dataset.go);if(b.dataset.pick){const id=b.dataset.pick,meal=selectedMeal;$('#pickerDialog').close();openRecipe(id,pickerDay,meal?{...meal,recipeSnapshot:null}:null);}if(b.dataset.cook)cook(homeItems('meals').find(m=>m.id===b.dataset.cook));if(b.dataset.changeMeal){const m=homeItems('meals').find(m=>m.id===b.dataset.changeMeal);openPicker(m.due,m);}if(b.dataset.postpone){postponed=homeItems('tasks').find(t=>t.id===b.dataset.postpone);$('#postponeDate').value=postponed.due||today();$('#postponeError').textContent='';$('#postponeDialog').showModal();}if(b.dataset.skip)await complete('tasks',homeItems('tasks').find(t=>t.id===b.dataset.skip),true,true);if(b.id==='importRecipes')await importRecipes();if(b.id==='findUseSoon'){$('#recipeUseSoon').checked=true;navigate('meals');}});
 return {navigate,render,dashboard,renderWeek,prepareItem,itemFields,openPicker,openMeal,openRecipe,renderRecipe,shopping,transfer,complete,migrateLocal,migrateShared};
}
