import {dateKey,addDays,escapeHTML as esc} from './calendar-model.js';
export function parseQuickAdd(text,type,now=new Date()){
 let name=text.trim(),due='',time='';
 if(type==='groceries'){const m=name.match(/^(.+?),\s*(\d+(?:\.\d+)?)\s*(.*)$/);return {name:m?m[1].trim():name,amount:m?Number(m[2]):1,unit:m?.[3]||'each'};}
 const days=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];
 name=name.replace(/\b(today|tomorrow|sunday|monday|tuesday|wednesday|thursday|friday|saturday)\b/i,word=>{const lower=word.toLowerCase();due=dateKey(addDays(now,lower==='today'?0:lower==='tomorrow'?1:(days.indexOf(lower)-now.getDay()+7)%7||7));return '';});
 if(type==='event')name=name.replace(/\bat\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\b/i,(whole,h,m,period)=>{h=Number(h);if(h>23||Number(m||0)>59||period&&(h<1||h>12))return whole;if(period)h=h%12+(period.toLowerCase()==='pm'?12:0);time=String(h).padStart(2,'0')+':'+(m||'00');return '';});
 return {name:name.replace(/\s+/g,' ').trim(),due,time};
}
export function installQuickAdd({homeChange,homeItems,openEvent,toast}){
 document.body.insertAdjacentHTML('beforeend',`<dialog id="quickDialog" aria-labelledby="quickTitle"><form id="quickForm"><div class="dialog-heading"><h2 id="quickTitle">Quick Add</h2><button type="button" class="icon" data-close aria-label="Close Quick Add">×</button></div><label>Add to<select id="quickType"><option value="groceries">Shopping</option><option value="tasks">Tasks</option><option value="event">Calendar</option></select></label><label>What do you need?<input id="quickText" maxlength="500" placeholder="Milk, 2 cartons" list="quickRecent" required></label><datalist id="quickRecent"></datalist><button type="button" class="button" id="quickReview">Review details</button><section id="quickFields" class="hidden"><h3>Check before saving</h3><label>Name<input id="quickName" maxlength="200"></label><div id="quickQuantity" class="form-grid"><label>Quantity<input id="quickAmount" type="number" min="0.01" max="100000" step="any"></label><label>Unit<input id="quickUnit" maxlength="40"></label></div><label id="quickDueLabel">Date<input id="quickDue" type="date"></label><label id="quickTimeLabel">Time (24-hour)<input id="quickTime" type="time"></label><p id="quickHint" class="muted"></p><button class="primary" id="quickSave">Save</button></section><p id="quickError" class="error" role="alert"></p></form></dialog>`);
 const $=s=>document.querySelector(s);let reviewed=false;
 $('#pbAccountBtn').insertAdjacentHTML('beforebegin','<button class="button" id="quickAddBtn" aria-label="Quick Add">+ Add</button>');
 $('#quickAddBtn').onclick=()=>{$('#quickRecent').innerHTML=[...new Set(homeItems('groceries').map(i=>i.name))].slice(-20).map(n=>`<option value="${esc(n)}"></option>`).join('');$('#quickDialog').showModal();$('#quickText').focus();};
 const reset=()=>{reviewed=false;$('#quickFields').classList.add('hidden');$('#quickError').textContent='';$('#quickText').placeholder=({groceries:'Milk, 2 cartons',tasks:'Take out recycling tomorrow',event:'Dinner Friday at 19:00'})[$('#quickType').value];};
 $('#quickText').oninput=reset;$('#quickType').onchange=reset;
 $('#quickReview').onclick=()=>{const type=$('#quickType').value,p=parseQuickAdd($('#quickText').value,type);if(!p.name)return $('#quickError').textContent='Enter a name first.';reviewed=true;$('#quickFields').classList.remove('hidden');$('#quickName').value=p.name;$('#quickAmount').value=p.amount||1;$('#quickUnit').value=p.unit||'each';$('#quickDue').value=p.due||'';$('#quickTime').value=p.time||'';$('#quickQuantity').classList.toggle('hidden',type!=='groceries');$('#quickDueLabel').classList.toggle('hidden',type==='groceries');$('#quickTimeLabel').classList.toggle('hidden',type!=='event');$('#quickHint').textContent=type==='event'?'Check the date and 24-hour time. Next, choose the calendar and end time.':'';$('#quickSave').textContent=type==='event'?'Continue to event':'Save';$('#quickName').focus();};
 $('#quickForm').onsubmit=async e=>{e.preventDefault();if(!reviewed){$('#quickReview').click();return;}const type=$('#quickType').value,name=$('#quickName').value.trim(),due=$('#quickDue').value;$('#quickSave').disabled=true;try{if(!name)throw Error('Enter a name.');if(type==='event'){if(!due||!$('#quickTime').value)throw Error('Choose a date and time.');$('#quickDialog').close();openEvent(null,due,$('#quickTime').value);$('#eventTitle').value=name;return;}const item={id:crypto.randomUUID(),name,done:false};if(type==='groceries'){item.amount=Number($('#quickAmount').value);item.unit=$('#quickUnit').value.trim();if(!(item.amount>0)||!item.unit)throw Error('Check the quantity and unit.');}else Object.assign(item,{due,repeat:'none',priority:'normal'});await homeChange(type,item);$('#quickDialog').close();$('#quickForm').reset();reset();toast('Added to '+(type==='groceries'?'shopping':'tasks'));}catch(err){$('#quickError').textContent=err.message;}finally{$('#quickSave').disabled=false;}};
}
