import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root=path.dirname(fileURLToPath(import.meta.url));
const env=Object.fromEntries((fs.existsSync(path.join(root,'.env'))?fs.readFileSync(path.join(root,'.env'),'utf8'):'').split(/\r?\n/).filter(Boolean).map(x=>x.split(/=(.*)/s).slice(0,2)));
const port=env.PORT||process.env.PORT||3000, base=env.APP_BASE_URL||process.env.APP_BASE_URL||`http://localhost:${port}`;
const clientId=env.GOOGLE_CLIENT_ID||process.env.GOOGLE_CLIENT_ID, clientSecret=env.GOOGLE_CLIENT_SECRET||process.env.GOOGLE_CLIENT_SECRET;
const storePath=path.join(root,'.hearth-calendar-data.json');
const data=fs.existsSync(storePath)?JSON.parse(fs.readFileSync(storePath,'utf8')):{sessions:{},tokens:{},states:{}};
const persist=()=>fs.writeFileSync(storePath,JSON.stringify(data,null,2));
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('=')));
function session(req,res){let id=cookies(req).hearth_session;if(!id){id=crypto.randomUUID();res.setHeader('Set-Cookie',`hearth_session=${id}; HttpOnly; SameSite=Lax; Path=/`)}data.sessions[id]??={};return id}
function send(res,status,payload){res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(payload))}
function redirect(res,url){res.writeHead(302,{Location:url});res.end()}
async function body(req){let raw='';for await(const x of req)raw+=x;return raw?JSON.parse(raw):{}}
async function accessToken(sid){let token=data.tokens[sid];if(!token)throw Error('Google Calendar is not connected.');if(token.expiry>Date.now()+60_000)return token.access_token;let r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,grant_type:'refresh_token',refresh_token:token.refresh_token})});let fresh=await r.json();if(!r.ok)throw Error(fresh.error_description||'Could not refresh Google access.');data.tokens[sid]={...token,...fresh,expiry:Date.now()+fresh.expires_in*1000};persist();return fresh.access_token}
async function google(sid,url,options={}){let token=await accessToken(sid);let r=await fetch(`https://www.googleapis.com/calendar/v3${url}`,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}});if(r.status===204)return null;let json=await r.json();if(!r.ok)throw Error(json.error?.message||'Google Calendar request failed.');return json}
function toGoogle(e){let start=`${e.date}T${e.time||'00:00'}:00`,end=`${e.date}T${e.end||e.time||'01:00'}:00`;if(e.allDay){let next=new Date(e.date+'T12:00');next.setDate(next.getDate()+1);return {summary:e.title,location:e.location||undefined,description:e.notes||undefined,start:{date:e.date},end:{date:next.toISOString().slice(0,10)}}}return {summary:e.title,location:e.location||undefined,description:e.notes||undefined,start:{dateTime:start},end:{dateTime:end},reminders:e.reminder==='No notification'?{useDefault:false}:{useDefault:true}}}
function fromGoogle(e){let date=e.start.date||e.start.dateTime.slice(0,10), allDay=!!e.start.date;return {id:`g_${e.id}`,googleEventId:e.id,title:e.summary||'(No title)',date,time:allDay?'':e.start.dateTime?.slice(11,16)||'',end:allDay?'':e.end.dateTime?.slice(11,16)||'',allDay,location:e.location||'',notes:e.description||'',calendar:'mike',updated:e.updated}}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'};
http.createServer(async(req,res)=>{try{let url=new URL(req.url,base),sid=session(req,res);
 if(url.pathname==='/api/google/status')return send(res,200,{connected:!!data.tokens[sid],configured:!!(clientId&&clientSecret)});
 if(url.pathname==='/auth/google'){if(!clientId||!clientSecret)return redirect(res,'/?sync=configuration-required');let state=crypto.randomUUID();data.states[state]=sid;persist();let q=new URLSearchParams({client_id:clientId,redirect_uri:`${base}/auth/google/callback`,response_type:'code',scope:'https://www.googleapis.com/auth/calendar',access_type:'offline',prompt:'consent',state});return redirect(res,`https://accounts.google.com/o/oauth2/v2/auth?${q}`)}
 if(url.pathname==='/auth/google/callback'){let sidFromState=data.states[url.searchParams.get('state')];delete data.states[url.searchParams.get('state')];if(!sidFromState)return redirect(res,'/?sync=invalid-state');if(url.searchParams.get('error'))return redirect(res,'/?sync=cancelled');let tokenRes=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code:url.searchParams.get('code'),client_id:clientId,client_secret:clientSecret,redirect_uri:`${base}/auth/google/callback`,grant_type:'authorization_code'})});let token=await tokenRes.json();if(!tokenRes.ok)return redirect(res,'/?sync=failed');data.tokens[sidFromState]={...token,expiry:Date.now()+token.expires_in*1000};persist();res.setHeader('Set-Cookie',`hearth_session=${sidFromState}; HttpOnly; SameSite=Lax; Path=/`);return redirect(res,'/?sync=connected')}
 if(url.pathname==='/api/google/events'&&req.method==='GET'){let from=url.searchParams.get('from')||new Date(Date.now()-90*864e5).toISOString(),to=url.searchParams.get('to')||new Date(Date.now()+365*864e5).toISOString();let result=await google(sid,`/calendars/primary/events?singleEvents=true&orderBy=startTime&timeMin=${encodeURIComponent(from)}&timeMax=${encodeURIComponent(to)}`);return send(res,200,{events:result.items.filter(x=>x.status!=='cancelled').map(fromGoogle)});}
 if(url.pathname==='/api/google/events'&&req.method==='POST'){let event=await body(req),calendar=event.googleCalendarId||'primary',payload=toGoogle(event);let saved=event.googleEventId?await google(sid,`/calendars/${encodeURIComponent(calendar)}/events/${encodeURIComponent(event.googleEventId)}`,{method:'PUT',body:JSON.stringify(payload)}):await google(sid,`/calendars/${encodeURIComponent(calendar)}/events`,{method:'POST',body:JSON.stringify(payload)});return send(res,200,{googleEventId:saved.id,updated:saved.updated});}
 if(url.pathname.startsWith('/api/google/events/')&&req.method==='DELETE'){let id=decodeURIComponent(url.pathname.split('/').pop());await google(sid,`/calendars/primary/events/${encodeURIComponent(id)}`,{method:'DELETE'});return send(res,204,{})}
 let file=url.pathname==='/'?'index.html':url.pathname.slice(1);let full=path.resolve(root,file);if(!full.startsWith(root)||!fs.existsSync(full)||fs.statSync(full).isDirectory())return send(res,404,{error:'Not found'});res.writeHead(200,{'Content-Type':mime[path.extname(full)]||'application/octet-stream'});fs.createReadStream(full).pipe(res);
}catch(error){console.error(error);send(res,500,{error:error.message||'Server error'})}}).listen(port,()=>console.log(`Hearth Calendar running at ${base}`));
