import fs from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {chromium} from '@playwright/test';
import {recipes} from '../recipes.js';
const root=fileURLToPath(new URL('../',import.meta.url)),port=3108;
const server=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,PORT:String(port),APP_BASE_URL:`http://localhost:${port}`},windowsHide:true,stdio:['ignore','pipe','pipe']});
let browser;
try{
 await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Preview server did not start.')),10000);server.once('error',reject);server.once('exit',code=>{clearTimeout(timeout);reject(Error('Preview server exited: '+code));});server.stdout.once('data',()=>{clearTimeout(timeout);resolve();});});
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000},timezoneId:'America/Chicago'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.clock.install({time:new Date('2026-09-15T14:00:00Z')});
 await page.addInitScript(recipes=>{const id=()=>crypto.randomUUID();localStorage.setItem('hearth-home',JSON.stringify({legacyRecipeMigrationComplete:true,tasks:[{id:id(),kind:'tasks',name:'Water the plants',due:'2026-09-15',assignedTo:'device',repeat:'weekly'},{id:id(),kind:'tasks',name:'Pick up the dry cleaning',due:'2026-09-15'},{id:id(),kind:'tasks',name:'Book a weekend getaway',due:'2026-09-18'}],meals:[{id:id(),kind:'meals',name:recipes[0].name,recipeId:recipes[0].id,recipeSnapshot:recipes[0],servings:2,due:'2026-09-15'},{id:id(),kind:'meals',name:recipes[1].name,recipeId:recipes[1].id,recipeSnapshot:recipes[1],servings:2,due:'2026-09-16'},{id:id(),kind:'meals',name:recipes[5].name,recipeId:recipes[5].id,recipeSnapshot:recipes[5],servings:2,due:'2026-09-18'}],groceries:[{id:id(),kind:'groceries',name:'Broccoli',amount:2,unit:'cup'},{id:id(),kind:'groceries',name:'Tomatoes',amount:4,unit:'each'},{id:id(),kind:'groceries',name:'Eggs',amount:12,unit:'each'},{id:id(),kind:'groceries',name:'Milk',amount:2,unit:'cup'},{id:id(),kind:'groceries',name:'Brown rice',amount:2,unit:'cup'}],pantry:[{id:id(),kind:'pantry',name:'Chicken',amount:300,unit:'g',expires:'2026-09-17'},{id:id(),kind:'pantry',name:'Spinach',amount:2,unit:'cup',expires:'2026-09-16'},{id:id(),kind:'pantry',name:'Olive oil',amount:10,unit:'tbsp'},{id:id(),kind:'pantry',name:'Brown rice',amount:2,unit:'cup'}]}));localStorage.setItem('hearth-events',JSON.stringify([{id:id(),title:'Morning walk together',date:'2026-09-15',endDate:'2026-09-15',time:'07:30',end:'08:00'},{id:id(),title:'Dinner with friends',date:'2026-09-15',endDate:'2026-09-15',time:'18:30',end:'20:00'}]));},recipes);
 await page.route('**/api/**',route=>route.fulfill({json:route.request().url().includes('/status')?{configured:true,connected:false}:{shared:false,items:[]}}));
 await fs.mkdir(new URL('../test-results/screenshots/',import.meta.url),{recursive:true});
 await page.goto(`http://localhost:${port}`);await page.locator('[data-app=home][aria-current=page]').waitFor();
 for(const device of ['desktop','mobile']){await page.setViewportSize(device==='desktop'?{width:1440,height:1000}:{width:390,height:844});for(const theme of ['light','dark']){await page.locator('#settingsBtn').click();await page.locator('#themeSelect').selectOption(theme);await page.getByRole('button',{name:'Close settings',exact:true}).click();for(const destination of ['Home','Calendar','Tasks','Meals','Shopping']){await page.getByRole('button',{name:destination,exact:true}).click();if(destination==='Calendar')await page.selectOption('#viewSelect',device==='mobile'?'day':'week');await page.screenshot({path:fileURLToPath(new URL(`../test-results/screenshots/${device}-${destination.toLowerCase()}-${theme}.png`,import.meta.url))});}}}
 if(errors.length)throw Error(errors.join('\n'));console.log('Captured 20 desktop/mobile screenshots in test-results/screenshots.');
}finally{await browser?.close();server.kill();}
